config = YAML::load(File.open("#{File.dirname(__FILE__)}/../config/pork_config.yml"))

http_auth_string = config['config']['twitter_auth']['username'] + ":" + config['config']['twitter_auth']['password'] + "@"
auth_and_no_auth = [http_auth_string, ""]


FakeWeb.allow_net_connect = false

# SEARCH METHOD 
FakeWeb.register_uri(:any, "http://search.twitter.com/search.json?rpp=100&q=test", :body => '{"results":[{"profile_image_url":"http://a3.twimg.com/profile_images/521281029/DSC01483_-_Kopia_-_Kopia_normal.JPG","created_at":"Wed, 11 Nov 2009 17:52:11 +0000","from_user":"SamIsMarth","to_user_id":10186853,"text":"@sage2526 cool. I have to study to my german test... Have a nice evening ^^","id":5624810553,"from_user_id":72123474,"to_user":"sage2526","geo":null,"iso_language_code":"en","source":"&lt;a href=&quot;http://twitter.com/&quot;&gt;web&lt;/a&gt;"},{"profile_image_url":"http://a3.twimg.com/profile_images/56115537/Andrew_-_small_normal.jpg","created_at":"Wed, 11 Nov 2009 17:52:09 +0000","from_user":"MarthIsGreat","to_user_id":null,"text":"Gearing up yo fail this calculus III test. Wish me luck!","id":5624809937,"from_user_id":842449,"geo":null,"iso_language_code":"en","source":"&lt;a href=&quot;http://help.twitter.com/index.php?pg=kb.page&amp;id=75&quot; rel=&quot;nofollow&quot;&gt;txt&lt;/a&gt;"}],"max_id":5624810553,"since_id":0,"refresh_url":"?since_id=5624810553&q=test","next_page":"?page=2&max_id=5624810553&q=test","results_per_page":15,"page":1,"completed_in":0.040758,"query":"test"}')

FakeWeb.register_uri(:any, "http://search.twitter.com/search.json?max_id=5624809937&rpp=100&q=test", :body => '{"results":[{"profile_image_url":"http://a3.twimg.com/profile_images/521281029/DSC01483_-_Kopia_-_Kopia_normal.JPG","created_at":"Wed, 11 Nov 2009 17:52:11 +0000","from_user":"EvanIsLucas","to_user_id":10186853,"text":"@sage2526 cool. I have to study to my german test... Have a nice evening ^^","id":1234567,"from_user_id":72123474,"to_user":"sage2526","geo":null,"iso_language_code":"en","source":"&lt;a href=&quot;http://twitter.com/&quot;&gt;web&lt;/a&gt;"},{"profile_image_url":"http://a3.twimg.com/profile_images/56115537/Andrew_-_small_normal.jpg","created_at":"Wed, 11 Nov 2009 17:52:09 +0000","from_user":"LucasIsCheap","to_user_id":null,"text":"Gearing up yo fail this calculus III test. Wish me luck!","id":5555,"from_user_id":842449,"geo":null,"iso_language_code":"en","source":"&lt;a href=&quot;http://help.twitter.com/index.php?pg=kb.page&amp;id=75&quot; rel=&quot;nofollow&quot;&gt;txt&lt;/a&gt;"}],"max_id":5624810553,"since_id":0,"refresh_url":"?since_id=5624810553&q=test","next_page":"?page=2&max_id=5624810553&q=test","results_per_page":15,"page":1,"completed_in":0.040758,"query":"test"}')

FakeWeb.register_uri(:any, "http://search.twitter.com/search.json?max_id=5555&rpp=100&q=test", :body => '{"results":[{"profile_image_url":"http://a3.twimg.com/profile_images/56115537/Andrew_-_small_normal.jpg","created_at":"Wed, 11 Nov 2009 17:52:09 +0000","from_user":"LucasIsCheap","to_user_id":null,"text":"Gearing up yo fail this calculus III test. Wish me luck!","id":5555,"from_user_id":842449,"geo":null,"iso_language_code":"en","source":"&lt;a href=&quot;http://help.twitter.com/index.php?pg=kb.page&amp;id=75&quot; rel=&quot;nofollow&quot;&gt;txt&lt;/a&gt;"}],"max_id":5624810553,"since_id":0,"refresh_url":"?since_id=5624810553&q=test","next_page":"?page=2&max_id=5624810553&q=test","results_per_page":15,"page":1,"completed_in":0.040758,"query":"test"}')
 
auth_and_no_auth.each do |auth_string| 
# USER INFO METHOD 
FakeWeb.register_uri(:any, "http://#{auth_string}twitter.com/users/show/15019521.json", :body => '{"following":false,"statuses_count":260,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme3/bg.gif","description":"","profile_link_color":"088253","status":{"in_reply_to_screen_name":null,"source":"web","created_at":"Tue Nov 10 15:22:43 +0000 2009","in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5590958294,"favorited":false,"text":"NEW POST (on my new, if still half-baked site), in which I complain about having too much money: www.samgilbert.org"},"geo_enabled":false,"profile_background_tile":false,"profile_background_color":"EDECE9","url":null,"verified":false,"profile_sidebar_fill_color":"E3E2DE","followers_count":132,"created_at":"Thu Jun 05 15:47:02 +0000 2008","time_zone":"Eastern Time (US & Canada)","friends_count":133,"profile_sidebar_border_color":"D3D2CF","protected":false,"profile_image_url":"http://a1.twimg.com/profile_images/55090134/samiamdrseuss_normal.jpg","location":"Cambridge, MA","name":"Sam Gilbert","notifications":false,"favourites_count":0,"screen_name":"sam1vp","id":15019521,"utc_offset":-18000,"profile_text_color":"634047"}')



# FOLLOWERS USER INFO METHOD
FakeWeb.register_uri(:any, "http://#{auth_string}twitter.com/statuses/followers.json?cursor=-1&user_id=15019521", :body => '{"users":[{"following":null,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme1/bg.png","description":"Bars, bartenders & imbibing in Beantown","verified":false,"profile_link_color":"0000ff","status":{"in_reply_to_screen_name":null,"source":"<a href=\"http://www.tweetdeck.com/\" rel=\"nofollow\">TweetDeck</a>","created_at":"Wed Nov 11 23:16:53 +0000 2009","in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5632679977,"favorited":false,"text":"What does one absolutely HAVE to do when visiting Seattle?"},"profile_background_tile":false,"profile_background_color":"9ae4e8","url":"http://drinkboston.com/","followers_count":343,"profile_sidebar_fill_color":"e0ff92","statuses_count":112,"created_at":"Sat Jun 13 11:24:47 +0000 2009","friends_count":141,"time_zone":"Quito","profile_sidebar_border_color":"87bc44","protected":false,"profile_image_url":"http://a3.twimg.com/profile_images/428011343/lauren_normal.jpg","notifications":null,"favourites_count":0,"location":"Boston, MA","name":"Lauren Clark","screen_name":"Drinkboston","id":55555,"geo_enabled":false,"utc_offset":-18000,"profile_text_color":"000000"},{"following":false,"geo_enabled":false,"statuses_count":114,"description":"Atlantic senior editor, James Beard Award-winner, and curator of The Atlantic Food Channel.","profile_image_url":"http://a1.twimg.com/profile_images/130071282/corby_mug_yellow_normal.png","status":{"in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"favorited":false,"in_reply_to_screen_name":null,"source":"<a href=\"http://twitterfeed.com\" rel=\"nofollow\">twitterfeed</a>","created_at":"Mon Nov 09 16:51:45 +0000 2009","id":5562998741,"text":"LAST OF THE ROMANOS My favorite green beans are at end-of-season farmers markets. Try them with this secret sa.. http://bit.ly/10jqzl"},"profile_background_tile":false,"profile_background_color":"9ae4e8","url":"http://drinkboston.com/","followers_count":343,"profile_sidebar_fill_color":"e0ff92","statuses_count":112,"created_at":"Sat Jun 13 11:24:47 +0000 2009","friends_count":141,"time_zone":"Quito","profile_sidebar_border_color":"87bc44","protected":false,"profile_image_url":"http://a3.twimg.com/profile_images/428011343/lauren_normal.jpg","notifications":null,"favourites_count":0,"location":"Boston, MA","name":"Lauren Clark","screen_name":"Drinkboston","id":4444,"geo_enabled":false,"utc_offset":-18000,"profile_text_color":"000000"}], "next_cursor":55555, "previous_cursor":0 }')

FakeWeb.register_uri(:any, "http://#{auth_string}twitter.com/statuses/followers.json?cursor=55555&user_id=15019521", :body => '{"users":[{"following":null,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme1/bg.png","description":"Bars, bartenders & imbibing in Beantown","verified":false,"profile_link_color":"0000ff","status":{"in_reply_to_screen_name":null,"source":"<a href=\"http://www.tweetdeck.com/\" rel=\"nofollow\">TweetDeck</a>","created_at":"Wed Nov 11 23:16:53 +0000 2009","in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5632679977,"favorited":false,"text":"What does one absolutely HAVE to do when visiting Seattle?"},"profile_background_tile":false,"profile_background_color":"9ae4e8","url":"http://drinkboston.com/","followers_count":343,"profile_sidebar_fill_color":"e0ff92","statuses_count":112,"created_at":"Sat Jun 13 11:24:47 +0000 2009","friends_count":141,"time_zone":"Quito","profile_sidebar_border_color":"87bc44","protected":false,"profile_image_url":"http://a3.twimg.com/profile_images/428011343/lauren_normal.jpg","notifications":null,"favourites_count":0,"location":"Boston, MA","name":"Lauren Clark","screen_name":"Drinkboston","id":333,"geo_enabled":false,"utc_offset":-18000,"profile_text_color":"000000"},{"following":false,"geo_enabled":false,"statuses_count":114,"description":"Atlantic senior editor, James Beard Award-winner, and curator of The Atlantic Food Channel.","profile_image_url":"http://a1.twimg.com/profile_images/130071282/corby_mug_yellow_normal.png","status":{"in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"favorited":false,"in_reply_to_screen_name":null,"source":"<a href=\"http://twitterfeed.com\" rel=\"nofollow\">twitterfeed</a>","created_at":"Mon Nov 09 16:51:45 +0000 2009","id":5562998741,"text":"LAST OF THE ROMANOS My favorite green beans are at end-of-season farmers markets. Try them with this secret sa.. http://bit.ly/10jqzl"},"profile_background_tile":false,"profile_background_color":"9ae4e8","url":"http://drinkboston.com/","followers_count":343,"profile_sidebar_fill_color":"e0ff92","statuses_count":112,"created_at":"Sat Jun 13 11:24:47 +0000 2009","friends_count":141,"time_zone":"Quito","profile_sidebar_border_color":"87bc44","protected":false,"profile_image_url":"http://a3.twimg.com/profile_images/428011343/lauren_normal.jpg","notifications":null,"favourites_count":0,"location":"Boston, MA","name":"Lauren Clark","screen_name":"Drinkboston","id":22,"geo_enabled":false,"utc_offset":-18000,"profile_text_color":"000000"}], "next_cursor":0, "previous_cursor":0 }')

FakeWeb.register_uri(:any, "http://#{auth_string}twitter.com/statuses/followers.json?cursor=-1&user_id=55555", :body => '{"users":[{"following":null,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme1/bg.png","description":"Bars, bartenders & imbibing in Beantown","verified":false,"profile_link_color":"0000ff","status":{"in_reply_to_screen_name":null,"source":"<a href=\"http://www.tweetdeck.com/\" rel=\"nofollow\">TweetDeck</a>","created_at":"Wed Nov 11 23:16:53 +0000 2009","in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5632679977,"favorited":false,"text":"What does one absolutely HAVE to do when visiting Seattle?"},"profile_background_tile":false,"profile_background_color":"9ae4e8","url":"http://drinkboston.com/","followers_count":343,"profile_sidebar_fill_color":"e0ff92","statuses_count":112,"created_at":"Sat Jun 13 11:24:47 +0000 2009","friends_count":141,"time_zone":"Quito","profile_sidebar_border_color":"87bc44","protected":false,"profile_image_url":"http://a3.twimg.com/profile_images/428011343/lauren_normal.jpg","notifications":null,"favourites_count":0,"location":"Boston, MA","name":"Lauren Clark","screen_name":"Drinkboston","id":333,"geo_enabled":false,"utc_offset":-18000,"profile_text_color":"000000"}], "next_cursor":0, "previous_cursor":0 }')

FakeWeb.register_uri(:any, "http://#{auth_string}twitter.com/statuses/followers.json?cursor=-1&user_id=4444", :body => '{"users":[{"following":null,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme1/bg.png","description":"Bars, bartenders & imbibing in Beantown","verified":false,"profile_link_color":"0000ff","status":{"in_reply_to_screen_name":null,"source":"<a href=\"http://www.tweetdeck.com/\" rel=\"nofollow\">TweetDeck</a>","created_at":"Wed Nov 11 23:16:53 +0000 2009","in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5632679977,"favorited":false,"text":"What does one absolutely HAVE to do when visiting Seattle?"},"profile_background_tile":false,"profile_background_color":"9ae4e8","url":"http://drinkboston.com/","followers_count":343,"profile_sidebar_fill_color":"e0ff92","statuses_count":112,"created_at":"Sat Jun 13 11:24:47 +0000 2009","friends_count":141,"time_zone":"Quito","profile_sidebar_border_color":"87bc44","protected":false,"profile_image_url":"http://a3.twimg.com/profile_images/428011343/lauren_normal.jpg","notifications":null,"favourites_count":0,"location":"Boston, MA","name":"Lauren Clark","screen_name":"Drinkboston","id":333,"geo_enabled":false,"utc_offset":-18000,"profile_text_color":"000000"}], "next_cursor":0, "previous_cursor":0 }')

FakeWeb.register_uri(:any, "http://#{auth_string}twitter.com/statuses/followers.json?cursor=-1&user_id=333", :body => '{"users":[{"following":null,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme1/bg.png","description":"Bars, bartenders & imbibing in Beantown","verified":false,"profile_link_color":"0000ff","status":{"in_reply_to_screen_name":null,"source":"<a href=\"http://www.tweetdeck.com/\" rel=\"nofollow\">TweetDeck</a>","created_at":"Wed Nov 11 23:16:53 +0000 2009","in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5632679977,"favorited":false,"text":"What does one absolutely HAVE to do when visiting Seattle?"},"profile_background_tile":false,"profile_background_color":"9ae4e8","url":"http://drinkboston.com/","followers_count":343,"profile_sidebar_fill_color":"e0ff92","statuses_count":112,"created_at":"Sat Jun 13 11:24:47 +0000 2009","friends_count":141,"time_zone":"Quito","profile_sidebar_border_color":"87bc44","protected":false,"profile_image_url":"http://a3.twimg.com/profile_images/428011343/lauren_normal.jpg","notifications":null,"favourites_count":0,"location":"Boston, MA","name":"Lauren Clark","screen_name":"Drinkboston","id":333,"geo_enabled":false,"utc_offset":-18000,"profile_text_color":"000000"}], "next_cursor":0, "previous_cursor":0 }')

FakeWeb.register_uri(:any, "http://#{auth_string}twitter.com/statuses/followers.json?cursor=-1&user_id=22", :body => '{"users":[{"following":null,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme1/bg.png","description":"Bars, bartenders & imbibing in Beantown","verified":false,"profile_link_color":"0000ff","status":{"in_reply_to_screen_name":null,"source":"<a href=\"http://www.tweetdeck.com/\" rel=\"nofollow\">TweetDeck</a>","created_at":"Wed Nov 11 23:16:53 +0000 2009","in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5632679977,"favorited":false,"text":"What does one absolutely HAVE to do when visiting Seattle?"},"profile_background_tile":false,"profile_background_color":"9ae4e8","url":"http://drinkboston.com/","followers_count":343,"profile_sidebar_fill_color":"e0ff92","statuses_count":112,"created_at":"Sat Jun 13 11:24:47 +0000 2009","friends_count":141,"time_zone":"Quito","profile_sidebar_border_color":"87bc44","protected":false,"profile_image_url":"http://a3.twimg.com/profile_images/428011343/lauren_normal.jpg","notifications":null,"favourites_count":0,"location":"Boston, MA","name":"Lauren Clark","screen_name":"Drinkboston","id":1,"geo_enabled":false,"utc_offset":-18000,"profile_text_color":"000000"}], "next_cursor":0, "previous_cursor":0 }')

# FRIEND USER INFO METHOD
FakeWeb.register_uri(:any, "http://#{auth_string}twitter.com/statuses/friends.json?cursor=-1&user_id=15019521", :body => '{"users":[{"following":null,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme1/bg.png","description":"Bars, bartenders & imbibing in Beantown","verified":false,"profile_link_color":"0000ff","status":{"in_reply_to_screen_name":null,"source":"<a href=\"http://www.tweetdeck.com/\" rel=\"nofollow\">TweetDeck</a>","created_at":"Wed Nov 11 23:16:53 +0000 2009","in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5632679977,"favorited":false,"text":"What does one absolutely HAVE to do when visiting Seattle?"},"profile_background_tile":false,"profile_background_color":"9ae4e8","url":"http://drinkboston.com/","followers_count":343,"profile_sidebar_fill_color":"e0ff92","statuses_count":112,"created_at":"Sat Jun 13 11:24:47 +0000 2009","friends_count":141,"time_zone":"Quito","profile_sidebar_border_color":"87bc44","protected":false,"profile_image_url":"http://a3.twimg.com/profile_images/428011343/lauren_normal.jpg","notifications":null,"favourites_count":0,"location":"Boston, MA","name":"Lauren Clark","screen_name":"thing0","id":55555,"geo_enabled":false,"utc_offset":-18000,"profile_text_color":"000000"},{"following":false,"geo_enabled":false,"statuses_count":114,"description":"Atlantic senior editor, James Beard Award-winner, and curator of The Atlantic Food Channel.","profile_image_url":"http://a1.twimg.com/profile_images/130071282/corby_mug_yellow_normal.png","status":{"in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"favorited":false,"in_reply_to_screen_name":null,"source":"<a href=\"http://twitterfeed.com\" rel=\"nofollow\">twitterfeed</a>","created_at":"Mon Nov 09 16:51:45 +0000 2009","id":5562998741,"text":"LAST OF THE ROMANOS My favorite green beans are at end-of-season farmers markets. Try them with this secret sa.. http://bit.ly/10jqzl"},"profile_background_tile":false,"profile_background_color":"9ae4e8","url":"http://drinkboston.com/","followers_count":343,"profile_sidebar_fill_color":"e0ff92","statuses_count":112,"created_at":"Sat Jun 13 11:24:47 +0000 2009","friends_count":141,"time_zone":"Quito","profile_sidebar_border_color":"87bc44","protected":false,"profile_image_url":"http://a3.twimg.com/profile_images/428011343/lauren_normal.jpg","notifications":null,"favourites_count":0,"location":"Boston, MA","name":"Lauren Clark","screen_name":"Drinkboston","id":4444,"geo_enabled":false,"utc_offset":-18000,"profile_text_color":"000000"}], "next_cursor":55555, "previous_cursor":0 }')

FakeWeb.register_uri(:any, "http://#{auth_string}twitter.com/statuses/friends.json?cursor=55555&user_id=15019521", :body => '{"users":[{"following":null,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme1/bg.png","description":"Bars, bartenders & imbibing in Beantown","verified":false,"profile_link_color":"0000ff","status":{"in_reply_to_screen_name":null,"source":"<a href=\"http://www.tweetdeck.com/\" rel=\"nofollow\">TweetDeck</a>","created_at":"Wed Nov 11 23:16:53 +0000 2009","in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5632679977,"favorited":false,"text":"What does one absolutely HAVE to do when visiting Seattle?"},"profile_background_tile":false,"profile_background_color":"9ae4e8","url":"http://drinkboston.com/","followers_count":343,"profile_sidebar_fill_color":"e0ff92","statuses_count":112,"created_at":"Sat Jun 13 11:24:47 +0000 2009","friends_count":141,"time_zone":"Quito","profile_sidebar_border_color":"87bc44","protected":false,"profile_image_url":"http://a3.twimg.com/profile_images/428011343/lauren_normal.jpg","notifications":null,"favourites_count":0,"location":"Boston, MA","name":"Lauren Clark","screen_name":"thing1","id":333,"geo_enabled":false,"utc_offset":-18000,"profile_text_color":"000000"},{"following":false,"geo_enabled":false,"statuses_count":114,"description":"Atlantic senior editor, James Beard Award-winner, and curator of The Atlantic Food Channel.","profile_image_url":"http://a1.twimg.com/profile_images/130071282/corby_mug_yellow_normal.png","status":{"in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"favorited":false,"in_reply_to_screen_name":null,"source":"<a href=\"http://twitterfeed.com\" rel=\"nofollow\">twitterfeed</a>","created_at":"Mon Nov 09 16:51:45 +0000 2009","id":5562998741,"text":"LAST OF THE ROMANOS My favorite green beans are at end-of-season farmers markets. Try them with this secret sa.. http://bit.ly/10jqzl"},"profile_background_tile":false,"profile_background_color":"9ae4e8","url":"http://drinkboston.com/","followers_count":343,"profile_sidebar_fill_color":"e0ff92","statuses_count":112,"created_at":"Sat Jun 13 11:24:47 +0000 2009","friends_count":141,"time_zone":"Quito","profile_sidebar_border_color":"87bc44","protected":false,"profile_image_url":"http://a3.twimg.com/profile_images/428011343/lauren_normal.jpg","notifications":null,"favourites_count":0,"location":"Boston, MA","name":"Lauren Clark","screen_name":"Drinkboston","id":22,"geo_enabled":false,"utc_offset":-18000,"profile_text_color":"000000"}], "next_cursor":0, "previous_cursor":0 }')

FakeWeb.register_uri(:any, "http://#{auth_string}twitter.com/statuses/friends.json?cursor=-1&user_id=55555", :body => '{"users":[{"following":null,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme1/bg.png","description":"Bars, bartenders & imbibing in Beantown","verified":false,"profile_link_color":"0000ff","status":{"in_reply_to_screen_name":null,"source":"<a href=\"http://www.tweetdeck.com/\" rel=\"nofollow\">TweetDeck</a>","created_at":"Wed Nov 11 23:16:53 +0000 2009","in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5632679977,"favorited":false,"text":"What does one absolutely HAVE to do when visiting Seattle?"},"profile_background_tile":false,"profile_background_color":"9ae4e8","url":"http://drinkboston.com/","followers_count":343,"profile_sidebar_fill_color":"e0ff92","statuses_count":112,"created_at":"Sat Jun 13 11:24:47 +0000 2009","friends_count":141,"time_zone":"Quito","profile_sidebar_border_color":"87bc44","protected":false,"profile_image_url":"http://a3.twimg.com/profile_images/428011343/lauren_normal.jpg","notifications":null,"favourites_count":0,"location":"Boston, MA","name":"Lauren Clark","screen_name":"thing2","id":333,"geo_enabled":false,"utc_offset":-18000,"profile_text_color":"000000"}], "next_cursor":0, "previous_cursor":0 }')

FakeWeb.register_uri(:any, "http://#{auth_string}twitter.com/statuses/friends.json?cursor=-1&user_id=4444", :body => '{"users":[{"following":null,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme1/bg.png","description":"Bars, bartenders & imbibing in Beantown","verified":false,"profile_link_color":"0000ff","status":{"in_reply_to_screen_name":null,"source":"<a href=\"http://www.tweetdeck.com/\" rel=\"nofollow\">TweetDeck</a>","created_at":"Wed Nov 11 23:16:53 +0000 2009","in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5632679977,"favorited":false,"text":"What does one absolutely HAVE to do when visiting Seattle?"},"profile_background_tile":false,"profile_background_color":"9ae4e8","url":"http://drinkboston.com/","followers_count":343,"profile_sidebar_fill_color":"e0ff92","statuses_count":112,"created_at":"Sat Jun 13 11:24:47 +0000 2009","friends_count":141,"time_zone":"Quito","profile_sidebar_border_color":"87bc44","protected":false,"profile_image_url":"http://a3.twimg.com/profile_images/428011343/lauren_normal.jpg","notifications":null,"favourites_count":0,"location":"Boston, MA","name":"Lauren Clark","screen_name":"thing3","id":333,"geo_enabled":false,"utc_offset":-18000,"profile_text_color":"000000"}], "next_cursor":0, "previous_cursor":0 }')

FakeWeb.register_uri(:any, "http://#{auth_string}twitter.com/statuses/friends.json?cursor=-1&user_id=333", :body => '{"users":[{"following":null,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme1/bg.png","description":"Bars, bartenders & imbibing in Beantown","verified":false,"profile_link_color":"0000ff","status":{"in_reply_to_screen_name":null,"source":"<a href=\"http://www.tweetdeck.com/\" rel=\"nofollow\">TweetDeck</a>","created_at":"Wed Nov 11 23:16:53 +0000 2009","in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5632679977,"favorited":false,"text":"What does one absolutely HAVE to do when visiting Seattle?"},"profile_background_tile":false,"profile_background_color":"9ae4e8","url":"http://drinkboston.com/","followers_count":343,"profile_sidebar_fill_color":"e0ff92","statuses_count":112,"created_at":"Sat Jun 13 11:24:47 +0000 2009","friends_count":141,"time_zone":"Quito","profile_sidebar_border_color":"87bc44","protected":false,"profile_image_url":"http://a3.twimg.com/profile_images/428011343/lauren_normal.jpg","notifications":null,"favourites_count":0,"location":"Boston, MA","name":"Lauren Clark","screen_name":"thing4","id":333,"geo_enabled":false,"utc_offset":-18000,"profile_text_color":"000000"}], "next_cursor":0, "previous_cursor":0 }')

FakeWeb.register_uri(:any, "http://#{auth_string}twitter.com/statuses/friends.json?cursor=-1&user_id=22", :body => '{"users":[{"following":null,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme1/bg.png","description":"Bars, bartenders & imbibing in Beantown","verified":false,"profile_link_color":"0000ff","status":{"in_reply_to_screen_name":null,"source":"<a href=\"http://www.tweetdeck.com/\" rel=\"nofollow\">TweetDeck</a>","created_at":"Wed Nov 11 23:16:53 +0000 2009","in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5632679977,"favorited":false,"text":"What does one absolutely HAVE to do when visiting Seattle?"},"profile_background_tile":false,"profile_background_color":"9ae4e8","url":"http://drinkboston.com/","followers_count":343,"profile_sidebar_fill_color":"e0ff92","statuses_count":112,"created_at":"Sat Jun 13 11:24:47 +0000 2009","friends_count":141,"time_zone":"Quito","profile_sidebar_border_color":"87bc44","protected":false,"profile_image_url":"http://a3.twimg.com/profile_images/428011343/lauren_normal.jpg","notifications":null,"favourites_count":0,"location":"Boston, MA","name":"Lauren Clark","screen_name":"thing5","id":1,"geo_enabled":false,"utc_offset":-18000,"profile_text_color":"000000"}], "next_cursor":0, "previous_cursor":0 }')


end

# FRIEND IDS METHOD
FakeWeb.register_uri(:any, "http://#{http_auth_string}twitter.com/friends/ids.json?user_id=15019521", :body => '[55555,4444,15019521]')

FakeWeb.register_uri(:any, "http://#{http_auth_string}twitter.com/friends/ids.json?user_id=55555", :body => '[4444]')

FakeWeb.register_uri(:any, "http://#{http_auth_string}twitter.com/friends/ids.json?user_id=4444", :body => '[333, 22, 1]')

FakeWeb.register_uri(:any, "http://twitter.com/friends/ids/15019521.json", :body => '[55555,4444,15019521]')

FakeWeb.register_uri(:any, "http://twitter.com/friends/ids/55555.json", :body => '[4444]')

FakeWeb.register_uri(:any, "http://twitter.com/friends/ids/4444.json", :body => '[333, 22, 1]')

# FOLLLOWER IDS METHOD
FakeWeb.register_uri(:any, "http://#{http_auth_string}twitter.com/followers/ids.json?user_id=15019521", :body => '[55555,4444,15019521]')

FakeWeb.register_uri(:any, "http://#{http_auth_string}twitter.com/followers/ids.json?user_id=55555", :body => '[4444]')

FakeWeb.register_uri(:any, "http://#{http_auth_string}twitter.com/followers/ids.json?user_id=4444", :body => '[333, 22, 1]')

FakeWeb.register_uri(:any, "http://twitter.com/followers/ids/15019521.json", :body => '[55555,4444,15019521]')

FakeWeb.register_uri(:any, "http://twitter.com/followers/ids/55555.json", :body => '[4444]')

FakeWeb.register_uri(:any, "http://twitter.com/followers/ids/4444.json", :body => '[333, 22, 1]')


# USER TWEETS METHOD
FakeWeb.register_uri(:any, "http://#{http_auth_string}twitter.com/statuses/user_timeline.json?count=200&user_id=15019521", :body => %^[{"in_reply_to_screen_name":null,"source":"web","geo":null,"created_at":"Tue Nov 10 15:22:43 +0000 2009","user":{"following":false,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme3/bg.gif","description":"","profile_link_color":"088253","profile_background_tile":false,"followers_count":132,"profile_background_color":"EDECE9","url":null,"friends_count":133,"profile_sidebar_fill_color":"E3E2DE","notifications":false,"statuses_count":260,"favourites_count":0,"created_at":"Thu Jun 05 15:47:02 +0000 2008","time_zone":"Eastern Time (US & Canada)","profile_sidebar_border_color":"D3D2CF","protected":false,"profile_image_url":"http://a1.twimg.com/profile_images/55090134/samiamdrseuss_normal.jpg","geo_enabled":false,"location":"Cambridge, MA","name":"Sam Gilbert","screen_name":"sam1vp","id":15019521,"verified":false,"utc_offset":-18000,"profile_text_color":"634047"},"in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5590958294,"favorited":false,"text":"NEW POST (on my new, if still half-baked site), in which I complain about having too much money: www.samgilbert.org"}, {"in_reply_to_screen_name":null,"source":"web","geo":null,"created_at":"Tue Nov 10 15:22:43 +0000 2009","user":{"following":false,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme3/bg.gif","description":"","profile_link_color":"088253","profile_background_tile":false,"followers_count":132,"profile_background_color":"EDECE9","url":null,"friends_count":133,"profile_sidebar_fill_color":"E3E2DE","notifications":false,"statuses_count":260,"favourites_count":0,"created_at":"Thu Jun 05 15:47:02 +0000 2008","time_zone":"Eastern Time (US & Canada)","profile_sidebar_border_color":"D3D2CF","protected":false,"profile_image_url":"http://a1.twimg.com/profile_images/55090134/samiamdrseuss_normal.jpg","geo_enabled":false,"location":"Cambridge, MA","name":"Sam Gilbert","screen_name":"sam1vp","id":15019521,"verified":false,"utc_offset":-18000,"profile_text_color":"634047"},"in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5590958294,"favorited":false,"text":"NEW POST (on my new, if still half-baked site), in which I complain about having too much money: www.samgilbert.org"}  ]^)

FakeWeb.register_uri(:any, "http://#{http_auth_string}twitter.com/statuses/user_timeline.json?max_id=5590958294&count=200&user_id=15019521", :body => %^[{"in_reply_to_screen_name":null,"source":"web","geo":null,"created_at":"Tue Nov 10 15:22:43 +0000 2009","user":{"following":false,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme3/bg.gif","description":"","profile_link_color":"088253","profile_background_tile":false,"followers_count":132,"profile_background_color":"EDECE9","url":null,"friends_count":133,"profile_sidebar_fill_color":"E3E2DE","notifications":false,"statuses_count":260,"favourites_count":0,"created_at":"Thu Jun 05 15:47:02 +0000 2008","time_zone":"Eastern Time (US & Canada)","profile_sidebar_border_color":"D3D2CF","protected":false,"profile_image_url":"http://a1.twimg.com/profile_images/55090134/samiamdrseuss_normal.jpg","geo_enabled":false,"location":"Cambridge, MA","name":"Sam Gilbert","screen_name":"sam1vp","id":15019521,"verified":false,"utc_offset":-18000,"profile_text_color":"634047"},"in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5590958294,"favorited":false,"text":"NEW POST (on my new, if still half-baked site), in which I complain about having too much money: www.samgilbert.org"}, {"in_reply_to_screen_name":null,"source":"web","geo":null,"created_at":"Tue Nov 10 15:22:43 +0000 2009","user":{"following":false,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme3/bg.gif","description":"","profile_link_color":"088253","profile_background_tile":false,"followers_count":132,"profile_background_color":"EDECE9","url":null,"friends_count":133,"profile_sidebar_fill_color":"E3E2DE","notifications":false,"statuses_count":260,"favourites_count":0,"created_at":"Thu Jun 05 15:47:02 +0000 2008","time_zone":"Eastern Time (US & Canada)","profile_sidebar_border_color":"D3D2CF","protected":false,"profile_image_url":"http://a1.twimg.com/profile_images/55090134/samiamdrseuss_normal.jpg","geo_enabled":false,"location":"Cambridge, MA","name":"Sam Gilbert","screen_name":"sam1vp","id":15019521,"verified":false,"utc_offset":-18000,"profile_text_color":"634047"},"in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5555,"favorited":false,"text":"NEW POST (on my new, if still half-baked site), in which I complain about having too much money: www.samgilbert.org"}  ]^)

FakeWeb.register_uri(:any, "http://#{http_auth_string}twitter.com/statuses/user_timeline.json?max_id=5555&count=200&user_id=15019521", :body => %^[{"in_reply_to_screen_name":null,"source":"web","geo":null,"created_at":"Tue Nov 10 15:22:43 +0000 2009","user":{"following":false,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme3/bg.gif","description":"","profile_link_color":"088253","profile_background_tile":false,"followers_count":132,"profile_background_color":"EDECE9","url":null,"friends_count":133,"profile_sidebar_fill_color":"E3E2DE","notifications":false,"statuses_count":260,"favourites_count":0,"created_at":"Thu Jun 05 15:47:02 +0000 2008","time_zone":"Eastern Time (US & Canada)","profile_sidebar_border_color":"D3D2CF","protected":false,"profile_image_url":"http://a1.twimg.com/profile_images/55090134/samiamdrseuss_normal.jpg","geo_enabled":false,"location":"Cambridge, MA","name":"Sam Gilbert","screen_name":"sam1vp","id":15019521,"verified":false,"utc_offset":-18000,"profile_text_color":"634047"},"in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5590958294,"favorited":false,"text":"NEW POST (on my new, if still half-baked site), in which I complain about having too much money: www.samgilbert.org"}, {"in_reply_to_screen_name":null,"source":"web","geo":null,"created_at":"Tue Nov 10 15:22:43 +0000 2009","user":{"following":false,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme3/bg.gif","description":"","profile_link_color":"088253","profile_background_tile":false,"followers_count":132,"profile_background_color":"EDECE9","url":null,"friends_count":133,"profile_sidebar_fill_color":"E3E2DE","notifications":false,"statuses_count":260,"favourites_count":0,"created_at":"Thu Jun 05 15:47:02 +0000 2008","time_zone":"Eastern Time (US & Canada)","profile_sidebar_border_color":"D3D2CF","protected":false,"profile_image_url":"http://a1.twimg.com/profile_images/55090134/samiamdrseuss_normal.jpg","geo_enabled":false,"location":"Cambridge, MA","name":"Sam Gilbert","screen_name":"sam1vp","id":15019521,"verified":false,"utc_offset":-18000,"profile_text_color":"634047"},"in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5555,"favorited":false,"text":"NEW POST (on my new, if still half-baked site), in which I complain about having too much money: www.samgilbert.org"}  ]^)

FakeWeb.register_uri(:any, "http://twitter.com/statuses/user_timeline/15019521.json?count=200", :body => %^[{"in_reply_to_screen_name":null,"source":"web","geo":null,"created_at":"Tue Nov 10 15:22:43 +0000 2009","user":{"following":false,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme3/bg.gif","description":"","profile_link_color":"088253","profile_background_tile":false,"followers_count":132,"profile_background_color":"EDECE9","url":null,"friends_count":133,"profile_sidebar_fill_color":"E3E2DE","notifications":false,"statuses_count":260,"favourites_count":0,"created_at":"Thu Jun 05 15:47:02 +0000 2008","time_zone":"Eastern Time (US & Canada)","profile_sidebar_border_color":"D3D2CF","protected":false,"profile_image_url":"http://a1.twimg.com/profile_images/55090134/samiamdrseuss_normal.jpg","geo_enabled":false,"location":"Cambridge, MA","name":"Sam Gilbert","screen_name":"sam1vp","id":15019521,"verified":false,"utc_offset":-18000,"profile_text_color":"634047"},"in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5590958294,"favorited":false,"text":"NEW POST (on my new, if still half-baked site), in which I complain about having too much money: www.samgilbert.org"}, {"in_reply_to_screen_name":null,"source":"web","geo":null,"created_at":"Tue Nov 10 15:22:43 +0000 2009","user":{"following":false,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme3/bg.gif","description":"","profile_link_color":"088253","profile_background_tile":false,"followers_count":132,"profile_background_color":"EDECE9","url":null,"friends_count":133,"profile_sidebar_fill_color":"E3E2DE","notifications":false,"statuses_count":260,"favourites_count":0,"created_at":"Thu Jun 05 15:47:02 +0000 2008","time_zone":"Eastern Time (US & Canada)","profile_sidebar_border_color":"D3D2CF","protected":false,"profile_image_url":"http://a1.twimg.com/profile_images/55090134/samiamdrseuss_normal.jpg","geo_enabled":false,"location":"Cambridge, MA","name":"Sam Gilbert","screen_name":"sam1vp","id":15019521,"verified":false,"utc_offset":-18000,"profile_text_color":"634047"},"in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5590958294,"favorited":false,"text":"NEW POST (on my new, if still half-baked site), in which I complain about having too much money: www.samgilbert.org"}  ]^)

FakeWeb.register_uri(:any, "http://twitter.com/statuses/user_timeline/15019521.json?max_id=5590958294&count=200", :body => %^[{"in_reply_to_screen_name":null,"source":"web","geo":null,"created_at":"Tue Nov 10 15:22:43 +0000 2009","user":{"following":false,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme3/bg.gif","description":"","profile_link_color":"088253","profile_background_tile":false,"followers_count":132,"profile_background_color":"EDECE9","url":null,"friends_count":133,"profile_sidebar_fill_color":"E3E2DE","notifications":false,"statuses_count":260,"favourites_count":0,"created_at":"Thu Jun 05 15:47:02 +0000 2008","time_zone":"Eastern Time (US & Canada)","profile_sidebar_border_color":"D3D2CF","protected":false,"profile_image_url":"http://a1.twimg.com/profile_images/55090134/samiamdrseuss_normal.jpg","geo_enabled":false,"location":"Cambridge, MA","name":"Sam Gilbert","screen_name":"sam1vp","id":15019521,"verified":false,"utc_offset":-18000,"profile_text_color":"634047"},"in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5590958294,"favorited":false,"text":"NEW POST (on my new, if still half-baked site), in which I complain about having too much money: www.samgilbert.org"}, {"in_reply_to_screen_name":null,"source":"web","geo":null,"created_at":"Tue Nov 10 15:22:43 +0000 2009","user":{"following":false,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme3/bg.gif","description":"","profile_link_color":"088253","profile_background_tile":false,"followers_count":132,"profile_background_color":"EDECE9","url":null,"friends_count":133,"profile_sidebar_fill_color":"E3E2DE","notifications":false,"statuses_count":260,"favourites_count":0,"created_at":"Thu Jun 05 15:47:02 +0000 2008","time_zone":"Eastern Time (US & Canada)","profile_sidebar_border_color":"D3D2CF","protected":false,"profile_image_url":"http://a1.twimg.com/profile_images/55090134/samiamdrseuss_normal.jpg","geo_enabled":false,"location":"Cambridge, MA","name":"Sam Gilbert","screen_name":"sam1vp","id":15019521,"verified":false,"utc_offset":-18000,"profile_text_color":"634047"},"in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5555,"favorited":false,"text":"NEW POST (on my new, if still half-baked site), in which I complain about having too much money: www.samgilbert.org"}  ]^)

FakeWeb.register_uri(:any, "http://twitter.com/statuses/user_timeline/15019521.json?max_id=5555&count=200", :body => %^[{"in_reply_to_screen_name":null,"source":"web","geo":null,"created_at":"Tue Nov 10 15:22:43 +0000 2009","user":{"following":false,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme3/bg.gif","description":"","profile_link_color":"088253","profile_background_tile":false,"followers_count":132,"profile_background_color":"EDECE9","url":null,"friends_count":133,"profile_sidebar_fill_color":"E3E2DE","notifications":false,"statuses_count":260,"favourites_count":0,"created_at":"Thu Jun 05 15:47:02 +0000 2008","time_zone":"Eastern Time (US & Canada)","profile_sidebar_border_color":"D3D2CF","protected":false,"profile_image_url":"http://a1.twimg.com/profile_images/55090134/samiamdrseuss_normal.jpg","geo_enabled":false,"location":"Cambridge, MA","name":"Sam Gilbert","screen_name":"sam1vp","id":15019521,"verified":false,"utc_offset":-18000,"profile_text_color":"634047"},"in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5590958294,"favorited":false,"text":"NEW POST (on my new, if still half-baked site), in which I complain about having too much money: www.samgilbert.org"}, {"in_reply_to_screen_name":null,"source":"web","geo":null,"created_at":"Tue Nov 10 15:22:43 +0000 2009","user":{"following":false,"profile_background_image_url":"http://s.twimg.com/a/1257800794/images/themes/theme3/bg.gif","description":"","profile_link_color":"088253","profile_background_tile":false,"followers_count":132,"profile_background_color":"EDECE9","url":null,"friends_count":133,"profile_sidebar_fill_color":"E3E2DE","notifications":false,"statuses_count":260,"favourites_count":0,"created_at":"Thu Jun 05 15:47:02 +0000 2008","time_zone":"Eastern Time (US & Canada)","profile_sidebar_border_color":"D3D2CF","protected":false,"profile_image_url":"http://a1.twimg.com/profile_images/55090134/samiamdrseuss_normal.jpg","geo_enabled":false,"location":"Cambridge, MA","name":"Sam Gilbert","screen_name":"sam1vp","id":15019521,"verified":false,"utc_offset":-18000,"profile_text_color":"634047"},"in_reply_to_user_id":null,"in_reply_to_status_id":null,"truncated":false,"id":5555,"favorited":false,"text":"NEW POST (on my new, if still half-baked site), in which I complain about having too much money: www.samgilbert.org"}  ]^)
